### ISSUE TITLE
Inconsistency in Ruby symbol with TreeSitter

### ISSUE THREAD

**Issue by foreverqihe** [atom/language-ruby#275] opened 2019-09-10 05:09 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. Open a ruby file, e.g. test.rb
2. write:

```ruby
%i[a b c]
:abc
```

**Expected behavior:**

The 2 lines of code are both symbols, so they should be the same color. 

**Actual behavior:**

The first line is orange/yellow. But if I turn off the TreeSitter, they are in the same color.

**Reproduces how often:**

Always

### Versions

C:\Windows\System32>atom --version

Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

### Additional Information
C:\Windows\System32>apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python 3.7.0
git 2.18.0.windows.1
visual studio

**Comment by rsese** [comment] 2019-09-10 23:29
Thanks for the report!  I believe this was fixed in https://github.com/atom/language-ruby/pull/271 - with 1.40.1 I can reproduce what you describe:

![ruby-tree-sitter-1 40 1](https://user-images.githubusercontent.com/734194/64657351-99f79300-d3f8-11e9-98a1-eff311bc03bc.png)

But with 1.42.0-nightly6 I see:

![ruby-tree-sitter-1 42 0-nightly6](https://user-images.githubusercontent.com/734194/64657364-a8de4580-d3f8-11e9-82d2-2608bb694ff7.png)

Going to go ahead and close as a duplicate of https://github.com/atom/language-ruby/issues/270 but if I misunderstood anything, please let me know.

**Closed by rsese** 2019-09-10 23:29 UTC
