### ISSUE TITLE
Regex causes Gray (discolored) for large portion of Beginning

### ISSUE THREAD

**Issue by jeff-hykin** [atom/language-ruby#286] opened 2020-06-22 20:02 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

The discoloration has some pretty strange behavior, it seems like a rendering problem instead of a parsing problem. It's a pretty big bug but I couldn't find a pre-existing issue for it.

Top of file is discolored, but (see next)
![Screen Shot 2020-06-22 at 2 48 53 PM](https://user-images.githubusercontent.com/17692058/85329206-ae90ad80-b497-11ea-8ccb-9da3d8041ddd.png)

coloration is resumed a bit further down.
![Screen Shot 2020-06-22 at 2 48 47 PM](https://user-images.githubusercontent.com/17692058/85329256-c6683180-b497-11ea-9b0c-39d280193c51.png)

### Steps to Reproduce

1. `atom --safe`
2. Select language Ruby
3. Paste the following code
```
require 'atk_toolbox'
require 'nokogiri'
require 'open-uri'
require 'statistics2' 

# this gets its value from the info.yaml file
$info = Info.new # load the info.yaml

$paths = $info.paths
path_to_urls = $paths['all_urls']
PARAMETERS = $info['parameters']

def force_explicit_pathing(path)
    if FS.absolute_path?(path)
        File.join("/",path) 
    else
        File.join("./",path)
    end
end

def relative_path(from:nil, to:nil)
    Pathname.new(to).relative_path_from(Pathname.new(from))
end

def get_video_ids_for(url)
    return Hash[ Nokogiri::HTML.parse(open(url).read).css('*').map{ |each| each['href'] =~ /^\/watch\?v=([^\&]+)/ && $1 }.compact.collect{ |item| [item, {}] } ]
end

def get_full_url(video_id)
    "https://www.youtube.com/watch?v=" + video_id
end

def get_metadata_for(url)
    result = `youtube-dl -j '#{url}' 2>&1`
    known_errors = [
        "ERROR: This video has been removed for violating YouTube's Community Guidelines",
        "ERROR: This live stream recording is not available",
        "ERROR: This video is unavailable",
    ]
    if result =~ /#{known_errors.join("|")}/
        return {
            unavailable: true,
        }
    end
    all_data = JSON.load(result)
    return {
        # title: all_data["title"],
        # description: all_data["description"],
        # categories: all_data["categories"],
        # tags: all_data["tags"],
        # subtitles: all_data["subtitles"],
        # automatic_captions: all_data["automatic_captions"],
        # view_count: all_data["view_count"],
        duration: all_data["duration"],
        fps: all_data["fps"],
        height: all_data["height"],
        width: all_data["width"],
    }
end

class Numeric
    def percent
        return self/100.0
    end
end

def confidence_interval(total_num_of_trys, num_of_successes, confidence:0.95)
    return 0 if total_num_of_trys == 0
    
    p_hat                     = 1.0*num_of_successes / total_num_of_trys
    # num_of_negative_events    = total_num_of_trys - num_of_successes
    # positive_deviation        = num_of_successes * ((1 - p_hat) ** 2)
    # negative_deviation        = num_of_negative_events * ((0 - p_hat) ** 2)
    # variance                  = (positive_deviation + negative_deviation) / (total_num_of_trys - 1)
    # sample_standard_deviation = Math.sqrt(variance)
    # estimated_stdev           = sample_standard_deviation / Math.sqrt(total_num_of_trys)
    allowable_error           = 1 - confidence
    allowable_error_per_side  = allowable_error / 2
    one_sided_confidence      = 1 - allowable_error_per_side
    
    z                   = Statistics2.pnormaldist(one_sided_confidence)
    z_squared_per_event = z*z / total_num_of_trys
    main_p_hat          = p_hat             + z_squared_per_event/2
    inverse_p_hat       = p_hat*(1-p_hat)   + z_squared_per_event/4
    
    top_part    = main_p_hat - z * Math.sqrt(inverse_p_hat/total_num_of_trys)
    bottom_part = 1 + z_squared_per_event
    lower_bound = top_part / bottom_part
    difference  = p_hat - lower_bound
    upper_bound = difference + p_hat
    return [lower_bound, upper_bound]
end
```

### Versions
```
language-ruby: 0.72.23
Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

### Additional Information

1. Adding a space to the end of a line (or otherwise editing it) updates it.
![Screen Shot 2020-06-22 at 2 49 01 PM](https://user-images.githubusercontent.com/17692058/85329842-e5b38e80-b498-11ea-862f-36f31154ead4.png)

2. Reloading the window does sometimes resolves the issue. Could be possible the problem is beyond the language-ruby package.

3. This issue doesn't occur when switching the syntax from "Ruby" to "Ruby on Rails"

**Comment by SampsonCrowley** [comment] 2020-07-01 16:55
Same problem with the exact same versions of Atom, Electron, Chrome, and Node (Arch Linux x64)

**Comment by ngelx** [comment] 2020-08-02 07:14
Same here

**Comment by ozydingo** [comment] 2020-09-24 10:16
I've narrowed this down to regex parsing in my case.

With a dummy variable assigned as a string, we've got no problem:

<img width="800" alt="Screen Shot 2020-09-24 at 6 10 05 AM" src="https://user-images.githubusercontent.com/4616431/94132144-df80d580-fe2c-11ea-815a-dada714b16bd.png">

Add a regex with a special character class and that line goes white:

<img width="800" alt="Screen Shot 2020-09-24 at 6 13 00 AM" src="https://user-images.githubusercontent.com/4616431/94132375-35557d80-fe2d-11ea-804f-d5a01fe141ed.png">

Save, close, and reopen, and the whole file is while:

<img width="800" alt="Screen Shot 2020-09-24 at 6 13 05 AM" src="https://user-images.githubusercontent.com/4616431/94132393-3d152200-fe2d-11ea-98a6-4fc1a93dccb6.png">

Same issue does not occur with a simpler regex (plain `d` character instead of `\d` char class)

<img width="800" alt="Screen Shot 2020-09-24 at 6 13 17 AM" src="https://user-images.githubusercontent.com/4616431/94132404-44d4c680-fe2d-11ea-87d5-97d0c072f8be.png">

Or with a regular character after the `\d`:

<img width="800" alt="Screen Shot 2020-09-24 at 6 15 52 AM" src="https://user-images.githubusercontent.com/4616431/94132517-6b92fd00-fe2d-11ea-9e66-94f48457c7c8.png">

**Comment by ozydingo** [comment] 2020-09-24 10:17
Seems like my observations may be consistent with the use of `\$` above.

**Comment by ozydingo** [comment] 2020-09-24 10:18
Interpolation also appears to affect this, as in the `/#{known_errors.join("|")}/` in OP's example

<img width="800" alt="Screen Shot 2020-09-24 at 6 17 31 AM" src="https://user-images.githubusercontent.com/4616431/94132725-b14fc580-fe2d-11ea-81ac-f73d33869b5c.png">

**Comment by ozydingo** [comment] 2020-09-24 10:21
Text in my example for ease of copy-paste:

```ruby
  def message(service, event)
    test = /\d/
    text = ":goodnews: *Service Inquiry Status Update*\n" \
      "Media File: <#{media_file_url(service.media_file)}|#{service.media_file&.display_name}>\n" \
      "#{service.type} <#{service_url(service)}|#{service.id}>\n" \
      "Event: #{event}"
    return prod? ? text : dev_tag + text
  end
```

**Comment by ozydingo** [comment] 2020-09-24 10:25
And I can confirm that the minimal example

```ruby
def foo
  /\d/
end
```

<img width="308" alt="Screen Shot 2020-09-24 at 6 24 39 AM" src="https://user-images.githubusercontent.com/4616431/94133463-aea1a000-fe2e-11ea-92b4-a03b53b4955a.png">

or even just

```ruby
/\d/
```

<img width="308" alt="Screen Shot 2020-09-24 at 6 24 45 AM" src="https://user-images.githubusercontent.com/4616431/94133476-b3665400-fe2e-11ea-9046-bf2bcdc60cc0.png">

triggers the issue.

**Comment by ozydingo** [comment] 2020-09-24 10:27
@jeff-hykin would it be appropriate to edit the title of this issue to something like "regex characters break syntax highlighting" to get some more focused eyes on this issue?

**Comment by jeff-hykin** [comment] 2020-09-24 10:47
Thanks for actually making progress on this @ozydingo 
I think I've seen an issue posted on Atom that describes this problem for multiple languages, so this should maybe be closed in favor of that one. However I can't seem to find that issue now.

**Comment by ozydingo** [comment] 2020-09-24 11:14
@jeff-hykin yup, [here](https://github.com/atom/atom/issues/21093) it is!

**Comment by ozydingo** [comment] 2020-09-24 11:17
It's *probably* the same issue, but I pause to close this since the syntax highlighting is not broken using `language-ruby-on-rails`, only `language-ruby`. If it's core to atom, I'm not sure why we would see that difference, but I could imagine up some scenarios sure. Still, I'd personally vote to leave this issue open given the slight possibility that this is in fact a `language-ruby`-specific issue.

**Comment by Aerijo** [comment] 2020-09-24 11:19
It is a Tree-sitter bug; `language-ruby-on-rails` is a TextMate grammar.

**Comment by darangi** [comment] 2021-02-04 19:07
This issue has been resolved [here](https://github.com/atom/atom/pull/21753)

You can get this fix in atom nightly before it gets to atom stable

**Closed by darangi** 2021-02-04 19:07 UTC
