### ISSUE TITLE
Syntax highlighting for method names in method chains is broken/different

### ISSUE THREAD

**Issue by ajaxm** [atom/language-ruby#246] opened 2018-10-26 21:17 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With tree-sitter enabled, method invocations in method chains are highlighted incorrectly. They share the same highlighting as method names in definitions. It's possible this was intentional, but it makes the code a lot harder to read. Screenshots below:

The old highlighting:
![screen shot 2018-10-26 at 2 10 16 pm](https://user-images.githubusercontent.com/13360138/47592626-e2b17500-d928-11e8-93c4-0233aa6bf068.png)

In the old case, the color of the method name in the definition is different from the color in the invocation. (Also the `puts` is a different color.)

The new highlighting:
![screen shot 2018-10-26 at 2 11 16 pm](https://user-images.githubusercontent.com/13360138/47592654-070d5180-d929-11e8-8385-7354c8d65b73.png)

In the new case, the color of the method name in the definition is the same as the color in the invocation. (Also the same color as `puts`).

### Steps to Reproduce

1. Open ruby file
1. Disable tree-sitter parsing in Core settings (on by default as of 1.32)
1. Save file
1. Syntax highlighting for method chains matches screenshot 1 above (the old way)
1. Re-enable tree-sitter parsing in Core settings
1. Save file
1. Syntax highlighting for method chains matches screenshot 2 above (the new way, potentially incorrect?)

**Expected behavior:** [What you expect to happen]
All method names in a method chain should be white (in the OneDark theme, for instance), or the same color.

**Actual behavior:** [What actually happens]
The first method name in a chain is white, while _all subsequent calls_ in the chain are blue.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom    : 1.32.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Ben3eeE** [comment] 2018-10-26 21:29
👋 Thank you for the report and apologies for the regression 🙇 

That `puts` has the same highlighting as the other functions seems like an unintentional change. `puts` is given `support.function.kernel` with textmate and `entity.name.function` with tree-sitter.

Do you have a reference of all the built in functions like `puts` that should be highlighted differently? I found [this reference](https://ruby-doc.org/docs/ruby-doc-bundle/Manual/man-1.4/function.html) online. Do you know if it's accurate?

I will open a PR to fix this as soon as I can.

I think that the call chain highlighting is an intentional change and I will have to ask @maxbrunsfeld about this 🙂

**Comment by ajaxm** [comment] 2018-10-26 21:30
@Ben3eeE FYI, one other thing:

With tree-sitter enabled, symbols have the same highlighting as constants and boolean literals. Symbols used to have a different highlighting.

The old highlighting:
![screen shot 2018-10-26 at 2 21 34 pm](https://user-images.githubusercontent.com/13360138/47593101-f1992700-d92a-11e8-8a20-db2a24001277.png)

The new highlighting:
![screen shot 2018-10-26 at 2 21 45 pm](https://user-images.githubusercontent.com/13360138/47593103-f3fb8100-d92a-11e8-9c13-d2d7622bfb16.png)

If I should make this as a new issue instead, pls let me know. Thanks!

**Comment by ajaxm** [comment] 2018-10-26 21:31
I don't have a reference but I'll look through the one you linked and double-check its accuracy. Thanks for looking into this!

**Comment by Ben3eeE** [comment] 2018-10-26 21:31
Symbols, constant literals and constant identifiers were fixed in https://github.com/atom/language-ruby/pull/244 and will go out in the next release.

If you have something that was not mentioned in the PR regarding this then please open a new issue 🙇

**Comment by ajaxm** [comment] 2018-10-26 21:52
A lot of the built-in functions are highlighted differently like `puts`, but not all, and I can't find any reference that details which ones should be.

Examples in the old highlighting:
![screen shot 2018-10-26 at 2 45 14 pm](https://user-images.githubusercontent.com/13360138/47593843-cc59e800-d92d-11e8-9a81-0385f4b8a955.png)

Same in new highlighting:
![screen shot 2018-10-26 at 2 46 02 pm](https://user-images.githubusercontent.com/13360138/47593866-e267a880-d92d-11e8-9101-55331b30bd7d.png)

`p`/`puts`/`print` are the obvious ones that have changed, but there are some weird cases:
1. `require`/`load` are reversed
1. `gsub`/`gsub!` and other such bang methods are now consistently highlighted, but it's because they're part of method chains. (From a personal preference, I do hope the new chain syntax isn't intentional! Or at least that they're different colors from the method definition.)
1. `binding` and `proc` are no longer highlighted at all

Idk how helpful all that is, but there's no definitive source that I can find. I don't think there was much consistency to begin with, so if the new way is different but consistent, that works too!

**Comment by maxbrunsfeld** [comment] 2018-10-26 21:57
I think that in general, it's a really good thing to highlight a given 'entity' (e.g. a method) the same every time that it appears. I think it really helps to give the colors actual meaning.

I think that in general, this was the intent all along, but the old TextMate parser was unable to do it consistently.

That said, if people  have strong preferences toward highlighting methods differently in different places, I don't want to break anyone's workflow. One thing we could do is add an additional class to the call site, which would not be styled by default, but you could customize your `style.css` to highlight it differently.

**Comment by maxbrunsfeld** [comment] 2018-10-26 21:57
We definitely intend to restore the different highlighting for certain "special" built-in functions like `require` and `puts`. I didn't intend to break that; apologies for not testing thoroughly enough.

**Comment by ajaxm** [comment] 2018-10-26 22:18
@maxbrunsfeld If you can add the additional class so that method chain highlighting works as before (even if it's not by default), I'd be really happy. I find that it's pretty hard to read, especially in larger/older codebases with lots of chaining, because pretty much all the text is suddenly blue.

For instance:
new way:
![screen shot 2018-10-26 at 3 14 27 pm](https://user-images.githubusercontent.com/13360138/47594802-e09fe400-d931-11e8-8151-2639affcda73.png)
old way:
![screen shot 2018-10-26 at 3 17 40 pm](https://user-images.githubusercontent.com/13360138/47594898-51470080-d932-11e8-8520-4570a1d609f2.png)


> I think that in general, it's a really good thing to highlight a given 'entity' (e.g. a method) the same every time that it appears. I think it really helps to give the colors actual meaning.

I don't think this is being consistently applied even in the new way. If the first call in a method chain is itself a method (like `booking` in the screenshot above), it's blue when it's defined but white when it's invoked.
On the other hand, if it was consistently implemented, every bit of text in the screenshot other than the local variable `service_end_time` (and words like def/end/etc) would be blue. I'm not sure I like that, and that's totally a preference, but if there's a way to customize my styles to avoid that, I'd find it really useful!

**Comment by npezza93** [comment] 2018-10-26 22:45
@maxbrunsfeld @Ben3eeE `defined?` was not included in that man page but was previous highlighted as a special word. Along with `alias`, and `alias_method`.

**Comment by maxbrunsfeld** [comment] 2018-10-27 20:52
I don't know, the old way doesn't seem any better; everything's just white, which is the same color as local variables. And `service` is oddly blue green in one place.

I do agree that the new way ends up having lots of blue. I guess this is because methods are used more in Ruby than in other languages. For example, in JavaScript, fields like `service_request`, `service`, and `actual_end_date` could have been public fields instead of methods, so they would appear in red instead of blue.

Another possible approach would be to use a different color for no-argument methods that don't end in `!`, like `.service_request` and `.service`, because those are likely to be simple accessors. Maybe we could color them similarly to properties (red, in this theme). That would make the ruby code look largely the same as the equivalent code in JavaScript, Java, etc. I could even imagine making an exception for method names starting with `to_`, because those aren't just accessors. That might be too complicated though.

@ajaxm thoughts?

**Comment by ajaxm** [comment] 2018-10-29 20:18
@maxbrunsfeld I don't really have a good answer. My main concern with the code being more blue than white was that I personally find white easier to read. You're right that this likely more of problem in Ruby than other languages.

And I agree that it *would* get complicated to color no-argument methods differently than other methods. It'd be hard to keep it meaningful, even if it's consistent: making a distinction between a "property" and a "function" in Ruby is probably not a good idea. For instance, I'd expect `cat.name` to look like a property (in red), and `cat.meow` or `cat.jump` to be functions (in blue), but there's no way the language package can know the difference between those no-argument methods.

**Comment by maxbrunsfeld** [comment] 2018-11-06 21:45
Ok, it sounds like the best fix is to add some additional class to method calls so that they can be styled differently from method definitions in your own personal stylesheet.

**Comment by maxbrunsfeld** [comment] 2018-11-06 21:45
Oops didn't mean to close this.

**Comment by snackattas** [comment] 2018-11-07 15:37
I think the syntax highlighting is broken? It keeps hopping into string highlighting when it's clearly code, not a string:
<img width="574" alt="11-07-2018 09 36 09_gsrc4f" src="https://user-images.githubusercontent.com/12533693/48141512-ab1fc280-e270-11e8-8863-01919cefade1.png">

**Comment by rbilar** [comment] 2018-11-22 19:08
Hi @maxbrunsfeld . I'm using Atom 1.32.2 and the problem that @snackattas commented on still happens to me. Can you tell me if I need to do anything else, besides updating Atom for the commented version?
Thank you
Ps.: Sorry about my english

**Closed** 2021-02-04 20:24 UTC
Labels: d ⬇️, i ⬇️, regression, tree-sitter, v ⬇️
