### ISSUE TITLE
Prefers "dop" snippet (with variable in block) over "do" snippet

### ISSUE THREAD

**Issue by stevehanson** [atom/language-ruby#131] opened 2016-01-22 14:29 UTC
This just started happening to me yesterday. When I'm writing a `do` block, it typically works like this: I write my code, then the word `do`, then `enter`. Language Ruby usually executes the `do` snippet which inserts the `end` keyword automatically and positions my cursor in the block.

Yesterday, the `dop` snippet started taking precedent, so that when I enter `do` and press enter, a variable section is created for the `do` block, and my cursor is in this area. I was wondering if there is any way to configure the order of which snippet takes precedent. I know I could hit the down arrow after typing `do` to choose the `do` snippet as you can see below, just wondering if there is a global config I could set or something.

![image](https://cloud.githubusercontent.com/assets/1691324/12513135/c36900bc-c0e1-11e5-9c0d-a6ce39b39200.png)

**Comment by abepetrillo** [comment] 2016-01-22 19:28
Same issue. Would prefer the variable option not be available.

**Comment by 50Wliu** [comment] 2016-01-22 20:34
This is a duplicate of #130 - please subscribe there for updates.  As a workaround you can disable the "Use Alternate Scoring" option in autocomplete-plus.

**Closed by 50Wliu** 2016-01-22 20:34 UTC

**Comment by stevehanson** [comment] 2016-01-22 21:41
@50Wliu thanks for pointing me in the right direction. Disabling "Use Alternate Scoring" did the trick for now. And sorry about the duplicate.
