### ISSUE TITLE
Failed to load a language-ruby package grammar

### ISSUE THREAD

**Issue by songmengmeng9** [atom/language-ruby#281] opened 2020-02-21 15:48 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: linux 3.10.0-1062.el7.x86_64
**Thrown From**: [language-ruby](https://github.com/atom/language-ruby) package 0.72.22

### Stack Trace

Failed to load a language-ruby package grammar

```
At /lib64/libstdc  .so.6: version `GLIBCXX_3.4.21' not found (required by /home/smm/Software/atom-1.44.0-amd64/resources/app.asar.unpacked/node_modules/tree-sitter-ruby/build/Release/tree_sitter_ruby_binding.node) in /home/smm/Software/atom-1.44.0-amd64/resources/app.asar/node_modules/language-ruby/grammars/tree-sitter-ruby.json

Error: /lib64/libstdc  .so.6: version `GLIBCXX_3.4.21' not found (required by /home/smm/Software/atom-1.44.0-amd64/resources/app.asar.unpacked/node_modules/tree-sitter-ruby/build/Release/tree_sitter_ruby_binding.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/home/smm/Software/atom-1.44.0-amd64/resources/app/static/<embedded>:11:146745)
    at /app.asar/node_modules/tree-sitter-ruby/index.js:2:20)
    at /app.asar/node_modules/tree-sitter-ruby/index.js:15:3)
    at Module.get_Module._compile (/home/smm/Software/atom-1.44.0-amd64/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/home/smm/Software/atom-1.44.0-amd64/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/home/smm/Software/atom-1.44.0-amd64/resources/app/static/<embedded>:1:694510)
    at new TreeSitterGrammar (/home/smm/Software/atom-1.44.0-amd64/resources/app/static/<embedded>:11:3134847)
    at GrammarRegistry.createGrammar (/home/smm/Software/atom-1.44.0-amd64/resources/app/static/<embedded>:11:359945)
    at l.readFile (/home/smm/Software/atom-1.44.0-amd64/resources/app/static/<embedded>:11:359786)
    at u (/home/smm/Software/atom-1.44.0-amd64/resources/app/static/<embedded>:11:580454)
    at /home/smm/Software/atom-1.44.0-amd64/resources/app/static/<embedded>:11:581707
    at fs.read.error (ELECTRON_ASAR.js:573:9)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:460:17)
  at /app.asar/node_modules/language-ruby/grammars/tree-sitter-ruby.json:1:1
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by Arcanemagus** [comment] 2020-02-21 18:46
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-ruby/issues/279. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2020-02-21 18:46 UTC
